[package]
name = "ww_global"
version = "0.2.0"
authors.workspace = true
description = "WireWeaver global type ID registry"
edition.workspace = true
license.workspace = true
repository = "https://github.com/vhrdtech/ww_stdlib"
documentation = "https://vhrdtech.github.io/wire_weaver/api/addressing/"

[features]
std = ["shrink_wrap/std"]
defmt = ["dep:defmt", "shrink_wrap/defmt"]
serde = ["dep:serde", "shrink_wrap/serde"]

[dependencies]
defmt = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
shrink_wrap.workspace = true

[build-dependencies]
convert_case.workspace = true
serde_json.workspace = true
