[package]
name = "ww_framer"
version.workspace = true
authors.workspace = true
description = "Packs many small WireWeaver messages into one packet or splits a big one across several"
edition.workspace = true
repository.workspace = true
license.workspace = true

[features]
std = ["shrink_wrap/std"]
large = []
very_large = []

[dependencies]
crc = "3.4"
shrink_wrap.workspace = true
