[package]
name = "wire_weaver_core"
edition = "2021"
version.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
syn = { workspace = true }
quote = { workspace = true }
proc-macro2 = { workspace = true }
strum = "0.26"
strum_macros = "0.26"
shrink_wrap = { path = "../shrink_wrap", default-features = false }
convert_case = "0.6"

[features]
default = ["std"]
std = ["shrink_wrap/std"]