[package]
name = "all_gpio"
version = "0.1.0"
publish = false
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
all_gpio_api.workspace = true
futures = "0.3"
tokio = { workspace = true, features = ["sync", "rt"] }
wire_weaver.workspace = true
wire_weaver_client.workspace = true
ww_gpio = { workspace = true, features = ["std"] }
ww_gpio_hl.workspace = true
ww_si = { workspace = true, features = ["std"] }

[dev-dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
console.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing = "0.1"
tracing-subscriber.workspace = true
ww_self = { workspace = true }
