//! Dynamic client (`wire_weaver_client::DynResource`, `ww_self::ValueOwned`) against the code generated by
//! `#[derive_shrink_wrap]` and `ww_codegen!`: same bytes on the wire, calls into a generated server.

#[cfg(test)]
mod tests {
    use dynamic_api::{
        CheckError, EverythingOwned, Fixed, FlaggedOwned, InnerOwned, ShapeOwned, Tagged,
    };
    use std::path::Path;
    use std::sync::Arc;
    use wire_weaver::prelude::*;
    use wire_weaver_client::ww_numeric::NumericValue::{self as N};
    use wire_weaver_client::ww_self::{ApiBundleOwned, FieldsValueOwned, TypeOwned, ValueOwned};
    use wire_weaver_client::{ClientConfig, DynClient, DynResource, DynResourceKind};

    mod server {
        use dynamic_api::{CheckError, Everything, Flagged};
        use tests_common::TestProcessEvents;
        use wire_weaver::prelude::*;
        use wire_weaver::{GetResult, SetResult};

        #[derive(Default)]
        pub struct DynServer {
            pub no_args_called: bool,
            speed: u16,
            gains: [f32; 3],
            /// Serialized `Everything`, as it borrows from the request and cannot be stored directly
            echo: Vec<u8>,
            everything: Vec<u8>,
            flagged: Vec<u8>,
        }

        fn to_bytes(value: &Everything<'_>) -> Vec<u8> {
            let mut buf = [0u8; 512];
            value.to_ww_bytes(&mut buf).unwrap().to_vec()
        }

        impl DynServer {
            fn no_args(&mut self, _cx: &mut Context<'_, impl BlockingEventOut>) -> RpcResult<()> {
                self.no_args_called = true;
                Ready(())
            }

            fn add(
                &mut self,
                _cx: &mut Context<'_, impl BlockingEventOut>,
                a: u32,
                b: i16,
            ) -> RpcResult<i64> {
                Ready(a as i64 + b as i64)
            }

            fn echo(
                &mut self,
                _cx: &mut Context<'_, impl BlockingEventOut>,
                value: Everything<'_>,
            ) -> RpcResult<Everything<'_>> {
                self.echo = to_bytes(&value);
                Ready(Everything::from_ww_bytes(&self.echo).unwrap())
            }

            fn check(
                &mut self,
                _cx: &mut Context<'_, impl BlockingEventOut>,
                x: Option<u8>,
            ) -> RpcResult<Result<u8, CheckError>> {
                Ready(match x {
                    None => Err(CheckError::Missing),
                    Some(x) if x > 100 => Err(CheckError::TooBig),
                    Some(x) => Ok(x),
                })
            }

            fn set_speed(
                &mut self,
                _cx: &mut Context<'_, impl BlockingEventOut>,
                value: u16,
            ) -> SetResult<()> {
                self.speed = value;
                Set
            }

            fn get_speed(
                &mut self,
                _cx: &mut Context<'_, impl BlockingEventOut>,
            ) -> GetResult<u16, ()> {
                Value(self.speed)
            }

            fn set_everything(
                &mut self,
                _cx: &mut Context<'_, impl BlockingEventOut>,
                value: Everything<'_>,
            ) -> SetResult<()> {
                self.everything = to_bytes(&value);
                Set
            }

            fn get_everything(
                &mut self,
                _cx: &mut Context<'_, impl BlockingEventOut>,
            ) -> GetResult<Everything<'_>, ()> {
                Value(Everything::from_ww_bytes(&self.everything).unwrap())
            }

            fn set_flagged(
                &mut self,
                _cx: &mut Context<'_, impl BlockingEventOut>,
                value: Flagged<'_>,
            ) -> SetResult<()> {
                let mut buf = [0u8; 64];
                self.flagged = value.to_ww_bytes(&mut buf).unwrap().to_vec();
                Set
            }

            fn get_flagged(
                &mut self,
                _cx: &mut Context<'_, impl BlockingEventOut>,
            ) -> GetResult<Flagged<'_>, ()> {
                Value(Flagged::from_ww_bytes(&self.flagged).unwrap())
            }

            fn valid_indices_root_channel(&mut self) -> ValidIndices<'_> {
                ValidIndices::range_u32(0..3)
            }

            fn set_channel_gain(
                &mut self,
                _cx: &mut Context<'_, impl BlockingEventOut>,
                index_chain: [UNib32; 1],
                value: f32,
            ) -> SetResult<()> {
                self.gains[index_chain[0].0 as usize] = value;
                Set
            }

            fn get_channel_gain(
                &mut self,
                _cx: &mut Context<'_, impl BlockingEventOut>,
                index_chain: [UNib32; 1],
            ) -> GetResult<f32, ()> {
                Value(self.gains[index_chain[0].0 as usize])
            }

            fn channel_id(
                &mut self,
                _cx: &mut Context<'_, impl BlockingEventOut>,
                index_chain: [UNib32; 1],
            ) -> RpcResult<u32> {
                Ready(index_chain[0].0 * 10)
            }
        }

        pub mod api_impl {
            wire_weaver::ww_codegen!(
                dynamic_api :: Dynamic for super::DynServer,
                server = true, no_alloc = true, use_async = false,
                method_model = "_=immediate",
                property_model = "_=get_set",
            );
        }

        impl TestProcessEvents for DynServer {
            type Medium = ();

            fn process_request_bytes<'a>(
                &mut self,
                bytes: &[u8],
                scratch: &'a mut [u8],
                out: &mut impl BlockingEventOut,
                medium: (),
            ) -> Result<&'a [u8], ShrinkWrapError> {
                self.process_request_bytes(bytes, scratch, out, medium)
            }
        }
    }

    fn bundle() -> Arc<ApiBundleOwned> {
        let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("../dynamic_api");
        Arc::new(wire_weaver_core::load(&path, Some("Dynamic".into()), false).unwrap())
    }

    fn everything() -> EverythingOwned {
        EverythingOwned {
            flag: true,
            small: U4::new(9).unwrap(),
            signed: I5::new(-7).unwrap(),
            nib: Nibble::new(0xA).unwrap(),
            v: UNib32(1234),
            a: 0xAB,
            b: 0xBEEF,
            c: 0xDEAD_BEEF,
            d: u64::MAX - 1,
            e: -5,
            f: -300,
            g: -70_000,
            h: i64::MIN + 1,
            x: 1.5,
            y: -2.25,
            name: "hello".into(),
            bytes: vec![1, 2, 3],
            arr: [1, 2, 0xFFFF],
            pair: (7, 100_000),
            opt: Some(InnerOwned {
                id: 3,
                note: "note".into(),
            }),
            res: Err(CheckError::Missing),
            shapes: vec![
                ShapeOwned::Empty,
                ShapeOwned::Circle(5),
                ShapeOwned::Rect {
                    w: 1,
                    h: 2,
                    label: "rect".into(),
                },
                ShapeOwned::Far,
            ],
            range: 3..10,
            fixed: Fixed { a: 9, b: true },
            last: U3::new(5).unwrap(),
        }
    }

    fn num(value: N) -> ValueOwned {
        ValueOwned::Numeric(value)
    }

    fn string(s: &str) -> ValueOwned {
        ValueOwned::String(s.into())
    }

    fn named(fields: Vec<(&str, ValueOwned)>) -> FieldsValueOwned {
        FieldsValueOwned::Named(fields.into_iter().map(|(n, v)| (n.into(), v)).collect())
    }

    fn strukt(fields: Vec<(&str, ValueOwned)>) -> ValueOwned {
        ValueOwned::Struct {
            fields: named(fields),
        }
    }

    fn variant(name: &str, fields: FieldsValueOwned) -> ValueOwned {
        ValueOwned::Enum {
            variant: name.into(),
            fields,
        }
    }

    /// Same as [everything], built independently of the derived types.
    fn everything_value() -> ValueOwned {
        strukt(vec![
            ("flag", ValueOwned::Bool(true)),
            ("small", num(N::U8(9))),
            ("signed", num(N::I8(-7))),
            ("nib", num(N::Nibble(Nibble::new(0xA).unwrap()))),
            ("v", num(N::UNib32(1234))),
            ("a", num(N::U8(0xAB))),
            ("b", num(N::U16(0xBEEF))),
            ("c", num(N::U32(0xDEAD_BEEF))),
            ("d", num(N::U64(u64::MAX - 1))),
            ("e", num(N::I8(-5))),
            ("f", num(N::I16(-300))),
            ("g", num(N::I32(-70_000))),
            ("h", num(N::I64(i64::MIN + 1))),
            ("x", num(N::F32(1.5))),
            ("y", num(N::F64(-2.25))),
            ("name", string("hello")),
            (
                "bytes",
                ValueOwned::Vec(vec![num(N::U8(1)), num(N::U8(2)), num(N::U8(3))]),
            ),
            (
                "arr",
                ValueOwned::Array(vec![num(N::U16(1)), num(N::U16(2)), num(N::U16(0xFFFF))]),
            ),
            (
                "pair",
                ValueOwned::Tuple(vec![num(N::U8(7)), num(N::U32(100_000))]),
            ),
            (
                "opt",
                ValueOwned::Option(Some(Box::new(strukt(vec![
                    ("id", num(N::U8(3))),
                    ("note", string("note")),
                ])))),
            ),
            (
                "res",
                ValueOwned::Result(Err(Box::new(variant("Missing", FieldsValueOwned::Unit)))),
            ),
            (
                "shapes",
                ValueOwned::Vec(vec![
                    variant("Empty", FieldsValueOwned::Unit),
                    variant("Circle", FieldsValueOwned::Unnamed(vec![num(N::U16(5))])),
                    variant(
                        "Rect",
                        named(vec![
                            ("w", num(N::U8(1))),
                            ("h", num(N::U8(2))),
                            ("label", string("rect")),
                        ]),
                    ),
                    variant("Far", FieldsValueOwned::Unit),
                ]),
            ),
            ("range", ValueOwned::Range(N::U16(3)..N::U16(10))),
            (
                "fixed",
                strukt(vec![("a", num(N::U8(9))), ("b", ValueOwned::Bool(true))]),
            ),
            ("last", num(N::U8(5))),
        ])
    }

    fn everything_ty(root: &DynResource) -> TypeOwned {
        let echo = root.child("echo").unwrap();
        let DynResourceKind::Method { args, .. } = echo.kind().unwrap() else {
            panic!("method expected");
        };
        args[0].ty.clone()
    }

    #[test]
    fn same_bytes_as_derived() {
        let root = DynResource::root(bundle());
        let ty = everything_ty(&root);
        let derived = everything().to_ww_bytes_owned().unwrap();

        let dynamic = everything_value()
            .ser_shrink_wrap_dyn(&ty, root.bundle())
            .unwrap();
        assert_eq!(dynamic, derived);

        let value = ValueOwned::des_shrink_wrap_dyn(&derived, &ty, root.bundle()).unwrap();
        assert_eq!(value, everything_value());
    }

    #[test]
    fn relocated_flags() {
        let root = DynResource::root(bundle());
        let flagged = root.child("flagged").unwrap();
        let DynResourceKind::Property { ty, .. } = flagged.kind().unwrap() else {
            panic!("property expected");
        };
        let some = |v: ValueOwned| ValueOwned::Option(Some(Box::new(v)));
        let none = ValueOwned::Option(None);
        let cases = [
            (
                FlaggedOwned {
                    a: U3::new(5).unwrap(),
                    early: Some("hi".into()),
                    res: Ok(7),
                    tagged: Tagged::Pair {
                        first: Some(1),
                        second: None,
                    },
                    late: Some(300),
                },
                vec![
                    ("a", num(N::U8(5))),
                    ("early", some(string("hi"))),
                    ("res", ValueOwned::Result(Ok(Box::new(num(N::U8(7)))))),
                    (
                        "tagged",
                        variant(
                            "Pair",
                            named(vec![
                                ("first", some(num(N::U8(1)))),
                                ("second", none.clone()),
                            ]),
                        ),
                    ),
                    ("late", some(num(N::U16(300)))),
                ],
            ),
            (
                FlaggedOwned {
                    a: U3::new(0).unwrap(),
                    early: None,
                    res: Err(CheckError::TooBig),
                    tagged: Tagged::Pair {
                        first: None,
                        second: Some(2),
                    },
                    late: None,
                },
                vec![
                    ("a", num(N::U8(0))),
                    ("early", none.clone()),
                    (
                        "res",
                        ValueOwned::Result(Err(Box::new(variant(
                            "TooBig",
                            FieldsValueOwned::Unit,
                        )))),
                    ),
                    (
                        "tagged",
                        variant(
                            "Pair",
                            named(vec![
                                ("first", none.clone()),
                                ("second", some(num(N::U8(2)))),
                            ]),
                        ),
                    ),
                    ("late", none.clone()),
                ],
            ),
        ];
        for (derived, value) in cases {
            let derived = derived.to_ww_bytes_owned().unwrap();
            let value = strukt(value);
            let dynamic = value.ser_shrink_wrap_dyn(ty, root.bundle()).unwrap();
            assert_eq!(dynamic, derived);
            let read = ValueOwned::des_shrink_wrap_dyn(&derived, ty, root.bundle()).unwrap();
            assert_eq!(read, value);
        }

        // flag of a missing Option field is written as None
        let partial = strukt(vec![
            ("a", num(N::U8(0))),
            ("res", ValueOwned::Result(Ok(Box::new(num(N::U8(1)))))),
            ("tagged", variant("Plain", FieldsValueOwned::Unit)),
        ]);
        let derived = FlaggedOwned {
            a: U3::new(0).unwrap(),
            early: None,
            res: Ok(1),
            tagged: Tagged::Plain,
            late: None,
        }
        .to_ww_bytes_owned()
        .unwrap();
        assert_eq!(
            partial.ser_shrink_wrap_dyn(ty, root.bundle()).unwrap(),
            derived
        );
    }

    #[test]
    fn same_bytes_as_derived_args() {
        let root = DynResource::root(bundle());
        let ty = everything_ty(&root);
        // `echo` args struct: one Unsized field, written with its size
        #[derive_shrink_wrap(owned)]
        struct EchoArgs {
            value: EverythingOwned,
        }
        let derived = EchoArgs {
            value: everything(),
        }
        .to_ww_bytes_owned()
        .unwrap();
        let dynamic = ValueOwned::ser_shrink_wrap_vec_dyn(
            &[everything_value()],
            [&ty].into_iter(),
            root.bundle(),
        )
        .unwrap();
        assert_eq!(dynamic, derived);
    }

    #[test]
    fn missing_option_field_is_none_and_errors_are_descriptive() {
        let root = DynResource::root(bundle());
        let ty = everything_ty(&root);
        let ValueOwned::Struct {
            fields: FieldsValueOwned::Named(mut fields),
        } = everything_value()
        else {
            unreachable!()
        };
        fields.retain(|(name, _)| name != "opt");
        let without_opt = ValueOwned::Struct {
            fields: FieldsValueOwned::Named(fields.clone()),
        };
        let bytes = without_opt.ser_shrink_wrap_dyn(&ty, root.bundle()).unwrap();
        let mut expected = everything();
        expected.opt = None;
        assert_eq!(bytes, expected.to_ww_bytes_owned().unwrap());

        fields.retain(|(name, _)| name != "a");
        let err = ValueOwned::Struct {
            fields: FieldsValueOwned::Named(fields),
        }
        .ser_shrink_wrap_dyn(&ty, root.bundle())
        .unwrap_err();
        assert!(format!("{err:#}").contains("missing field 'a'"), "{err:#}");

        let err = strukt(vec![("nope", ValueOwned::Bool(true))])
            .ser_shrink_wrap_dyn(&ty, root.bundle())
            .unwrap_err();
        assert!(
            format!("{err:#}").contains("does not have field 'nope'"),
            "{err:#}"
        );
    }

    #[test]
    fn out_of_range_numbers_are_rejected() {
        let root = DynResource::root(bundle());
        let add = root.child("add").unwrap();
        let DynResourceKind::Method { args, .. } = add.kind().unwrap() else {
            panic!()
        };
        let err = num(N::I64(-1))
            .ser_shrink_wrap_dyn(&args[0].ty, root.bundle())
            .unwrap_err();
        assert!(format!("{err}").contains("out of range"), "{err}");
        // wider variant is fine when the value fits
        let bytes = num(N::I64(70_000))
            .ser_shrink_wrap_dyn(&args[0].ty, root.bundle())
            .unwrap();
        assert_eq!(bytes, 70_000u32.to_ww_bytes_owned().unwrap());
    }

    #[test]
    fn walk_errors() {
        let root = DynResource::root(bundle());
        let err = root.child("nope").unwrap_err().to_string();
        assert!(err.contains("has no resource 'nope'"), "{err}");
        assert!(root.child("channel").unwrap().child("gain").is_err());
        let gain = root
            .child("channel")
            .unwrap()
            .index(2)
            .unwrap()
            .child("gain")
            .unwrap();
        assert_eq!(gain.path(), "channel[2].gain");
        assert_eq!(gain.index_chain().len(), 3);
    }

    #[tokio::test(flavor = "multi_thread", worker_threads = 2)]
    async fn calls_into_generated_server() {
        let device = tests_common::start_device(
            "dynamic",
            server::DynServer::default(),
            dynamic_api::DYNAMIC_FULL_GID,
            server::api_impl::api_hash(),
        );
        let client = DynClient::from_config(ClientConfig::new().in_process_path(device.path()))
            .connect()
            .await
            .expect("connect");
        let cmd = client.cmd();
        let root = DynResource::root(bundle());

        let r = root.child("no_args").unwrap().call(cmd, &[]).await.unwrap();
        assert_eq!(r, None);

        let r = root
            .child("add")
            .unwrap()
            .call(cmd, &[num(N::U32(40)), num(N::I16(-2))])
            .await
            .unwrap();
        assert_eq!(r, Some(num(N::I64(38))));

        let echo = root.child("echo").unwrap();
        let r = echo.call(cmd, &[everything_value()]).await.unwrap();
        assert_eq!(r, Some(everything_value()));
        let err = echo.call(cmd, &[]).await.unwrap_err().to_string();
        assert!(err.contains("takes 1 arguments, got 0"), "{err}");

        let check = root.child("check").unwrap();
        let ok = |v| Some(ValueOwned::Result(Ok(Box::new(v))));
        let err = |name| {
            Some(ValueOwned::Result(Err(Box::new(variant(
                name,
                FieldsValueOwned::Unit,
            )))))
        };
        let some = |v| ValueOwned::Option(Some(Box::new(num(N::U8(v)))));
        assert_eq!(
            check.call(cmd, &[some(5)]).await.unwrap(),
            ok(num(N::U8(5)))
        );
        assert_eq!(check.call(cmd, &[some(200)]).await.unwrap(), err("TooBig"));
        assert_eq!(
            check.call(cmd, &[ValueOwned::Option(None)]).await.unwrap(),
            err("Missing")
        );

        let speed = root.child("speed").unwrap();
        speed.write(cmd, &num(N::U16(1500))).await.unwrap();
        assert_eq!(speed.read(cmd).await.unwrap(), num(N::U16(1500)));

        let flagged = root.child("flagged").unwrap();
        let value = strukt(vec![
            ("a", num(N::U8(3))),
            ("early", ValueOwned::Option(None)),
            ("res", ok(num(N::U8(9))).unwrap()),
            (
                "tagged",
                variant("Pair", named(vec![("first", some(1)), ("second", some(2))])),
            ),
            ("late", ValueOwned::Option(Some(Box::new(num(N::U16(7)))))),
        ]);
        flagged.write(cmd, &value).await.unwrap();
        assert_eq!(flagged.read(cmd).await.unwrap(), value);

        let prop = root.child("everything").unwrap();
        prop.write(cmd, &everything_value()).await.unwrap();
        assert_eq!(prop.read(cmd).await.unwrap(), everything_value());

        let channel = root.child("channel").unwrap();
        let valid: Vec<u32> = channel.valid_indices(cmd).await.unwrap().iter().collect();
        assert_eq!(valid, vec![0, 1, 2]);
        let gain = channel.index(1).unwrap().child("gain").unwrap();
        gain.write(cmd, &num(N::F32(0.25))).await.unwrap();
        assert_eq!(gain.read(cmd).await.unwrap(), num(N::F32(0.25)));
        let other = channel.index(2).unwrap().child("gain").unwrap();
        assert_eq!(other.read(cmd).await.unwrap(), num(N::F32(0.0)));
        let id = channel.index(2).unwrap().child("id").unwrap();
        assert_eq!(id.call(cmd, &[]).await.unwrap(), Some(num(N::U32(20))));
    }
}
