[package]
name = "ww_log_bare_metal"
version = "0.1.0"
authors.workspace = true
description = "Baremetal logging types and API"
edition.workspace = true
license.workspace = true
repository = "https://github.com/vhrdtech/ww_stdlib"

[features]
default = ["std"]
std = ["wire_weaver/std", "ww_si/std"]
defmt = ["dep:defmt", "wire_weaver/defmt"]

[dependencies]
defmt = { workspace = true, optional = true }
wire_weaver.workspace = true
ww_si.workspace = true
