[package]
name = "wire_weaver_net_host"
edition.workspace = true
version.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
futures-util = "0.3"
shrink_wrap.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["sync", "net", "macros", "time"] }
tokio-tungstenite = "0.30"
tracing = "0.1"
wire_weaver_udp_link.workspace = true
