//! Server scaffold: a starting point for the user side of a server, with a stub for every handler
//! [gen_server](crate::gen_server) expects to be implemented on the server struct.
//!
//! Handler names and signatures must stay in sync with `codegen/api_server.rs`.
use crate::codegen::ty_def::{TyPos, ty_def};
use crate::method_model::{MethodModel, MethodModelKind};
use crate::property_model::{PropertyModel, PropertyModelKind};
use anyhow::{Context, Result};
use convert_case::{Case, Casing};
use std::fmt::Write;
use ww_numeric::{NumericAnyTypeOwned, NumericBaseType};
use ww_self::{
    ApiBundleOwned, ApiItemKindOwned, ApiItemOwned, ApiLevelOwned, Multiplicity, PropertyAccess,
    TypeOwned,
};

/// Server scaffold generation configuration, same meaning as the `ww_codegen!` arguments.
pub struct ServerScaffoldConfig {
    /// Name of the server struct to generate.
    pub server_struct: String,
    pub no_alloc: bool,
    pub use_async: bool,
    /// Empty means `_=immediate`.
    pub method_model: String,
    /// Empty means `_=get_set`.
    pub property_model: String,
}

/// Generates Rust source of a server struct, an impl block with a stub for every handler, each returning
/// `Unimplemented` (or doing nothing, where there is no result to return), and a `ww_codegen!` invocation
/// generating the server dispatcher for them.
///
/// The output is not formatted, run it through rustfmt.
pub fn gen_server_scaffold(
    api_bundle: &ApiBundleOwned,
    config: &ServerScaffoldConfig,
) -> Result<String> {
    let method_model_str = if config.method_model.is_empty() {
        "_=immediate"
    } else {
        config.method_model.as_str()
    };
    let property_model_str = if config.property_model.is_empty() {
        "_=get_set"
    } else {
        config.property_model.as_str()
    };
    let method_model =
        MethodModel::parse(method_model_str).context("failed to parse method model")?;
    let property_model =
        PropertyModel::parse(property_model_str).context("failed to parse property model")?;

    let root = &api_bundle.root;
    let crate_name = root.crate_name(api_bundle)?.replace('-', "_");
    let mut s = Scaffold {
        api_bundle,
        no_alloc: config.no_alloc,
        use_async: config.use_async,
        method_model,
        property_model,
        fields: String::new(),
        handlers: String::new(),
    };
    s.level(root, None, "root".into(), 0, "")?;

    let server = &config.server_struct;
    let trait_name = &root.trait_name;
    let mut out = String::new();
    writeln!(
        out,
        "// Server scaffold for `{crate_name}::{trait_name}`, generated by `ww api scaffold`.\n\
         // Every handler is a stub returning Unimplemented, replace them with real implementations.\n\
         use wire_weaver::prelude::*;\n"
    )?;
    writeln!(out, "pub struct {server} {{\n{}}}\n", s.fields)?;
    writeln!(out, "impl {server} {{\n{}}}\n", s.handlers)?;
    writeln!(
        out,
        "mod api_impl {{\n\
         wire_weaver::ww_codegen!(\n\
         {crate_name} :: {trait_name} for super::{server},\n\
         server = true, no_alloc = {}, use_async = {},\n\
         method_model = {method_model_str:?},\n\
         property_model = {property_model_str:?},\n\
         );\n\
         }}",
        config.no_alloc, config.use_async
    )?;
    Ok(out)
}

struct Scaffold<'a> {
    api_bundle: &'a ApiBundleOwned,
    no_alloc: bool,
    use_async: bool,
    method_model: MethodModel,
    property_model: PropertyModel,
    fields: String,
    handlers: String,
}

impl Scaffold<'_> {
    /// Mirrors `process_request_inner_recursive` and `level_matchers`: `prefix` is the chain of trait item
    /// idents handler names are prefixed with, `level_name_chain` is `root_<..>` used in valid indices handler
    /// names, `index_len` is the length of the index chain passed to handlers on this level.
    fn level(
        &mut self,
        level: &ApiLevelOwned,
        prefix: Option<&str>,
        level_name_chain: String,
        index_len: usize,
        path: &str,
    ) -> Result<()> {
        let crate_name = level.crate_name(self.api_bundle)?;
        let at = if path.is_empty() { "root" } else { path };
        writeln!(
            self.handlers,
            "// ---- {crate_name}::{} at {at} ----\n",
            level.trait_name
        )?;
        for item in &level.items {
            let is_array = matches!(item.multiplicity, Multiplicity::Array { .. });
            if is_array {
                self.valid_indices(item, &level_name_chain, index_len, path)?;
            }
            let item_index_len = index_len + is_array as usize;
            let name = match prefix {
                Some(prefix) => format!("{prefix}_{}", item.ident),
                None => item.ident.clone(),
            };
            match &item.kind {
                ApiItemKindOwned::Method { args, return_ty } => {
                    self.method(item, &name, item_index_len, args, return_ty)?
                }
                ApiItemKindOwned::Property {
                    ty,
                    access,
                    write_err_ty,
                } => self.property(item, &name, item_index_len, ty, *access, write_err_ty)?,
                ApiItemKindOwned::Stream { ty, is_up } => {
                    self.stream(item, &name, item_index_len, ty, *is_up)?
                }
                ApiItemKindOwned::Trait { .. } => {}
            }
        }
        for item in &level.items {
            if !matches!(item.kind, ApiItemKindOwned::Trait { .. }) {
                continue;
            }
            let is_array = matches!(item.multiplicity, Multiplicity::Array { .. });
            let child = item.get_as_level(self.api_bundle)?;
            let child_prefix = match prefix {
                Some(prefix) => format!("{prefix}_{}", item.ident),
                None => item.ident.clone(),
            };
            let child_path = format!(
                "{path}{}{}{}",
                if path.is_empty() { "" } else { "." },
                item.ident,
                if is_array { "[]" } else { "" }
            );
            self.level(
                child,
                Some(&child_prefix),
                format!("{level_name_chain}_{}", item.ident),
                index_len + is_array as usize,
                &child_path,
            )?;
        }
        Ok(())
    }

    fn valid_indices(
        &mut self,
        item: &ApiItemOwned,
        level_name_chain: &str,
        index_len: usize,
        path: &str,
    ) -> Result<()> {
        writeln!(
            self.handlers,
            "/// Valid indices of `{path}{}{}[]`.\n\
             fn valid_indices_{level_name_chain}_{}(&mut self, {}) -> ValidIndices<'_> {{\n\
             // TODO: no index is valid until implemented\n\
             ValidIndices::range_u32(0..0)\n\
             }}\n",
            if path.is_empty() { "" } else { "." },
            item.ident,
            item.ident.to_case(Case::Snake),
            index_chain_arg(index_len),
        )?;
        Ok(())
    }

    fn method(
        &mut self,
        item: &ApiItemOwned,
        name: &str,
        index_len: usize,
        args: &[ww_self::ArgumentOwned],
        return_ty: &Option<TypeOwned>,
    ) -> Result<()> {
        let mut args_def = String::new();
        for arg in args {
            // same as the args struct fields handlers are called with, see api_common::args_structs
            let ty = self.ty(&arg.ty, !self.no_alloc)?;
            write!(args_def, "_{}: {ty}, ", arg.ident)?;
        }
        let return_ty = match return_ty {
            Some(ty) => self.ty(ty, false)?,
            None => "()".into(),
        };
        self.docs(item)?;
        if self.method_model.pick(&item.ident) == Some(MethodModelKind::Deferred) {
            writeln!(
                self.handlers,
                "// method_model: deferred, return Deferred and send the result later"
            )?;
        }
        writeln!(
            self.handlers,
            "{}fn {name}(&mut self, _msg_tx: &mut impl MessageSink, {}{args_def}) -> RpcResult<{return_ty}> {{\n\
             Unimplemented.into()\n\
             }}\n",
            self.maybe_async(),
            index_chain_arg(index_len),
        )?;
        Ok(())
    }

    fn property(
        &mut self,
        item: &ApiItemOwned,
        name: &str,
        index_len: usize,
        ty: &TypeOwned,
        access: PropertyAccess,
        write_err_ty: &Option<TypeOwned>,
    ) -> Result<()> {
        let value_ty = self.ty(ty, false)?;
        let err_ty = match write_err_ty {
            Some(ty) => self.ty(ty, false)?,
            None => "()".into(),
        };
        let is_writable = matches!(
            access,
            PropertyAccess::WriteOnly | PropertyAccess::ReadWrite { .. }
        );
        let is_readable = !matches!(access, PropertyAccess::WriteOnly);
        let idx = index_chain_arg(index_len);
        let maybe_async = self.maybe_async();
        match self
            .property_model
            .pick(&item.ident)
            .unwrap_or(PropertyModelKind::GetSet)
        {
            PropertyModelKind::GetSet => {
                if is_writable {
                    self.docs(item)?;
                    writeln!(
                        self.handlers,
                        "{maybe_async}fn set_{name}(&mut self, {idx}_value: {value_ty}) -> SetResult<{err_ty}> {{\n\
                         Unimplemented.into()\n\
                         }}\n",
                    )?;
                }
                if is_readable {
                    self.docs(item)?;
                    writeln!(
                        self.handlers,
                        "{maybe_async}fn get_{name}(&mut self, {idx}) -> GetResult<{value_ty}, {err_ty}> {{\n\
                         Unimplemented.into()\n\
                         }}\n",
                    )?;
                }
            }
            PropertyModelKind::ValueOnChanged => {
                // generated code reads and writes `self.<name>[index_chain[0]]..` directly
                let field_ty = value_ty.replace("'_", "'static");
                for line in &item.docs {
                    writeln!(self.fields, "///{}", doc_line(line))?;
                }
                if index_len == 0 {
                    writeln!(self.fields, "pub {name}: {field_ty},")?;
                } else {
                    let mut array_ty = field_ty;
                    for i in (0..index_len).rev() {
                        array_ty = format!("[{array_ty}; N{i}]");
                    }
                    let indices: String = (0..index_len).map(|i| format!("[i{i}]")).collect();
                    writeln!(
                        self.fields,
                        "// TODO: indexed as self.{name}{indices}\n// pub {name}: {array_ty},"
                    )?;
                }
                if is_writable {
                    self.docs(item)?;
                    writeln!(
                        self.handlers,
                        "/// Called after `{name}` was changed by a client.\n\
                         {maybe_async}fn changed_{name}(&mut self, {idx}) {{}}\n",
                    )?;
                }
            }
        }
        Ok(())
    }

    fn stream(
        &mut self,
        item: &ApiItemOwned,
        name: &str,
        index_len: usize,
        ty: &TypeOwned,
        is_up: bool,
    ) -> Result<()> {
        let idx = index_chain_arg(index_len);
        let maybe_async = self.maybe_async();
        self.docs(item)?;
        writeln!(
            self.handlers,
            "{maybe_async}fn sideband_{name}(&mut self, _msg_tx: &mut impl MessageSink, {idx}_sideband: ww_client_server::StreamSideband) -> Option<ww_client_server::StreamSideband> {{\n\
             // TODO: None sends no reply\n\
             None\n\
             }}\n",
        )?;
        if !is_up {
            // same special cases as api_server::handle_stream
            let arg = match ty {
                TypeOwned::Tuple(elements) if elements.is_empty() => "_value: ()".into(),
                TypeOwned::Vec(inner)
                    if matches!(
                        inner.as_ref(),
                        TypeOwned::NumericAny(NumericAnyTypeOwned::Base(NumericBaseType::U8))
                    ) =>
                {
                    "_data: &shrink_wrap::tail_bytes::TailBytes<'_>".into()
                }
                _ => format!("_value: {}", self.ty(ty, false)?),
            };
            self.docs(item)?;
            writeln!(
                self.handlers,
                "{maybe_async}fn write_{name}(&mut self, {idx}{arg}) {{}}\n",
            )?;
        }
        Ok(())
    }

    fn docs(&mut self, item: &ApiItemOwned) -> Result<()> {
        for line in &item.docs {
            writeln!(self.handlers, "///{}", doc_line(line))?;
        }
        Ok(())
    }

    fn ty(&self, ty: &TypeOwned, alloc: bool) -> Result<String> {
        Ok(ty_def(self.api_bundle, ty, alloc, TyPos::Arg)?.to_string())
    }

    fn maybe_async(&self) -> &'static str {
        if self.use_async { "async " } else { "" }
    }
}

fn index_chain_arg(len: usize) -> String {
    if len == 0 {
        String::new()
    } else {
        format!("_index_chain: [UNib32; {len}], ")
    }
}

fn doc_line(line: &str) -> String {
    if line.is_empty() || line.starts_with(' ') {
        line.to_string()
    } else {
        format!(" {line}")
    }
}
