[package]
name = "properties"
version = "0.1.0"
publish = false
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = ["std"]
std = []

[dependencies]
hex-literal.workspace = true
properties_api.workspace = true
tests_common.workspace = true
tokio = { workspace = true, features = ["sync", "rt-multi-thread", "rt", "macros", "test-util"] }
tracing-subscriber.workspace = true
wire_weaver.workspace = true
wire_weaver_client.workspace = true
ww_client_server.workspace = true
