[package]
name = "properties"
version = "0.1.0"
edition = "2024"

[features]
default = ["std"]
std = []

[dependencies]
hex-literal = "1"
properties_api = { path = "../properties_api" }
tests_common = { path = "../tests_common" }
tokio = { version = "1", features = ["sync", "rt-multi-thread", "rt", "macros", "test-util"] }
tracing-subscriber = "0.3"
wire_weaver.workspace = true
wire_weaver_client_common.workspace = true
ww_client_server.workspace = true
