[package]
name = "ww_log_bare_metal"
version = "0.1.0"
authors.workspace = true
description = "Baremetal logging types and API"
edition.workspace = true

[dependencies]
wire_weaver = { path = "../wire_weaver", default-features = false }
defmt = { version = "1.0", optional = true }

[features]
default = ["std"]
std = ["wire_weaver/std"]
defmt = ["dep:defmt", "wire_weaver/defmt"]
