[package]
name = "wire_weaver_client"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[features]
default = ["usb"]
# default = ["usb", "net"]
usb = [] # USB (using nusb)
net = [] # WebSockets or UDP
can = [] # CAN Bus using USB or Ethernet to CAN bridges or socketcan on Linux
rtt = ["dep:probe-rs"] # RTT over JTAG/SWD
i2c = [] # I2C using USB or Ethernet to I2C bridges or kernel I2C interface on Linux
uart = [] # UART using USB or Ethernet to UART bridges or system provided serial ports
ipc = [] # inter-process communication channel (using iceoryx2)
in_process = [] # in-process channel

usb-tracing = [
    "dep:iceoryx2",
    "dep:iceoryx2-bb-container",
] # stream all USB packets over iceoryx2 to debugger

[dependencies]
anyhow.workspace = true
cfg-if = "1"
either = "1"
futures-lite = "2.6"
hex = { workspace = true, features = ["std"] }
iceoryx2 = { version = "0.8", optional = true }
iceoryx2-bb-container = { version = "0.8", optional = true }
nusb = { version = "0.2", features = ["tokio"] } # TODO: try to use without tokio?
probe-rs = { version = "0.32", default-features = false, features = ["builtin-targets", "cmsisdap_v1", "builtin-formats"], optional = true }
rand = "0.10"
ron.workspace = true
semver.workspace = true
strum.workspace = true
strum_macros.workspace = true
thiserror = "2.0"
tokio = { version = "1", features = ["sync", "rt", "time", "macros"] }
tracing = "0.1"
wire_weaver = { version = "0.4.0", path = "../wire_weaver" }
ww_client_server = { workspace = true, features = ["std"] }
ww_link = { path = "../ww_link", features = ["std"] }
ww_framer = { workspace = true, features = ["std", "large"] }
ww_self = { workspace = true, features = ["std", "serde"] }
ww_version = { workspace = true, features = ["std"] }
