# List all available targets
default:
    @just --list

# Supported boards: rp2; Supported binaries: usb_blinky and others from src/bin
run board bin *args:
    just "run-{{board}}-{{bin}}" {{args}}

run-rp2-blinky *args:
    cargo run --bin rp2_blinky {{args}}

run-rp2-usb_blinky *args:
    cargo run --bin rp2_usb_blinky --features "usb" {{args}}

run-rp2-ww_rtt *args:
    cargo run --bin rp2_ww_rtt --no-default-features --features="rtt_target"

run-rp2-ww_ws_ncm *args:
    cargo run --bin rp2_ww_ws_ncm --features "ws_ncm" {{args}}

run-rp2-ww_udp_ncm *args:
    cargo run --bin rp2_ww_udp_ncm --features "udp_ncm" {{args}}
