[package]
name = "wire_weaver_core"
edition = "2024"
version.workspace = true
authors.workspace = true
description = "Core types, AST and codegen of wire_weaver - API code generator for microcontrollers"
repository.workspace = true
license.workspace = true
documentation = "https://vhrdtech.github.io/wire_weaver"

[features]
default = ["std"]
std = ["shrink_wrap/std"]

[dependencies]
anyhow = "1"
cargo_toml = "1.0"
console = "0.16"
convert_case = "0.11"
hex = "0.4"
pest = "2.8"
pest_derive = { version = "2.8", features = ["grammar-extras"] }
proc-macro2 = { workspace = true }
quote = { workspace = true }
regex = "1.12"
relative-path = "2.0"
ron = "0.12"
semver.workspace = true
sha2 = "0.11"
shrink_wrap.workspace = true
shrink_wrap_core.workspace = true
syn = { workspace = true }
ww_numeric = { workspace = true, features = ["std", "serde"] }
ww_self = { workspace = true, features = ["std", "serde"] }
ww_version = { workspace = true, features = ["serde"] }
