[package]
name = "wire_weaver_core"
edition.workspace = true
version.workspace = true
authors.workspace = true
description = "Core types, AST and codegen of wire_weaver - API code generator for microcontrollers"
repository.workspace = true
license.workspace = true
documentation = "https://vhrdtech.github.io/wire_weaver"

[features]
default = ["std"]
std = ["shrink_wrap/std"]

[dependencies]
anyhow.workspace = true
cargo_toml = "1.0"
console.workspace = true
convert_case.workspace = true
hex = { workspace = true, features = ["std"] }
pest = "2.8"
pest_derive = { version = "2.8", features = ["grammar-extras"] }
proc-macro2 = { workspace = true }
quote = { workspace = true }
regex = "1.12"
relative-path.workspace = true
ron.workspace = true
semver.workspace = true
sha2.workspace = true
shrink_wrap.workspace = true
syn = { workspace = true }
wire_weaver_snapshots.workspace = true
ww_numeric = { workspace = true, features = ["std", "serde"] }
ww_self = { workspace = true, features = ["std", "serde"] }
ww_version = { workspace = true, features = ["serde"] }
