//! Dynamic (runtime, type-driven) serialization of [ValueOwned], producing the same bytes as the code generated by
//! `#[derive_shrink_wrap]` for the equivalent Rust types.
//!
//! Every value that is not a top-level one is written the way generated code writes a field (`BufWriter::write`):
//! the size of [Unsized](shrink_wrap::ElementSize::Unsized) types (evolvable structs and enums, `Box`) is recorded in
//! the FIFO of sizes at the back of the buffer, see [TypeOwned::is_unsized]. Top-level values (method return values,
//! property values, stream items) are written without it (`to_ww_bytes`), same as method arguments, which are the
//! fields of an evolvable struct.

use crate::{
    ApiBundleOwned, FieldOwned, FieldsOwned, FieldsValueOwned, ItemEnumOwned, Repr, TypeOwned,
    ValueOwned,
};
use anyhow::{Result, anyhow, bail};
use shrink_wrap::buf_writer_owned::UnsizedBuilderOwned;
use shrink_wrap::{BufReader, BufWriterOwned, Nibble};
use ww_numeric::{NumericAnyTypeOwned, NumericBaseType, NumericValue};

impl ValueOwned {
    /// Deserialize one top-level value of type `ty` (as `T::from_ww_bytes_owned` does).
    pub fn des_shrink_wrap_dyn(
        bytes: &[u8],
        ty: &TypeOwned,
        api_bundle: &ApiBundleOwned,
    ) -> Result<Self> {
        let mut rd = BufReader::new(bytes);
        des_inner(&mut rd, ty, api_bundle)
    }

    /// Serialize as one top-level value of type `ty` (as `to_ww_bytes_owned` does).
    pub fn ser_shrink_wrap_dyn(
        &self,
        ty: &TypeOwned,
        api_bundle: &ApiBundleOwned,
    ) -> Result<Vec<u8>> {
        let mut wr = BufWriterOwned::new();
        ser_inner(&mut wr, self, ty, api_bundle)?;
        Ok(wr.finish_and_take()?)
    }

    /// Serialize values as the fields of an evolvable struct, e.g., method arguments.
    pub fn ser_shrink_wrap_vec_dyn<'i>(
        values: &[ValueOwned],
        types: impl Iterator<Item = &'i TypeOwned>,
        api_bundle: &ApiBundleOwned,
    ) -> Result<Vec<u8>> {
        let mut wr = BufWriterOwned::new();
        let mut values = values.iter();
        for ty in types {
            let value = values
                .next()
                .ok_or(anyhow!("values and types must have the same length"))?;
            ser_field(&mut wr, value, ty, api_bundle)?;
        }
        if values.next().is_some() {
            bail!("values and types must have the same length");
        }
        Ok(wr.finish_and_take()?)
    }

    /// Deserialize the fields of an evolvable struct, e.g., method arguments.
    /// Missing trailing fields (sent by an older version) are an error, their types carry no default.
    pub fn des_shrink_wrap_vec_dyn<'i>(
        bytes: &[u8],
        types: impl Iterator<Item = &'i TypeOwned>,
        api_bundle: &ApiBundleOwned,
    ) -> Result<Vec<Self>> {
        let mut rd = BufReader::new(bytes);
        types.map(|ty| des_field(&mut rd, ty, api_bundle)).collect()
    }

    pub fn default(ty: &TypeOwned, api_bundle: &ApiBundleOwned) -> Result<Self> {
        match ty {
            TypeOwned::Bool => Ok(ValueOwned::Bool(false)),
            TypeOwned::NumericAny(any) => {
                Ok(ValueOwned::Numeric(default_numeric(numeric_base(any))?))
            }
            TypeOwned::OutOfLine { type_idx } => {
                let ty = api_bundle.get_ty(type_idx.0)?;
                Self::default(ty.0, api_bundle)
            }
            TypeOwned::Flag => Err(anyhow!("flag type cannot be created manually")),
            TypeOwned::String => Ok(ValueOwned::String(String::new())),
            TypeOwned::Vec(_) => Ok(ValueOwned::Vec(vec![])),
            TypeOwned::Array { len, ty } => {
                Ok(ValueOwned::Array(vec![
                    ValueOwned::default(ty, api_bundle)?;
                    len.0 as usize
                ]))
            }
            TypeOwned::Tuple(types) => {
                let mut values = vec![];
                for ty in types {
                    values.push(Self::default(ty, api_bundle)?);
                }
                Ok(ValueOwned::Tuple(values))
            }
            TypeOwned::Struct(item_struct) => Ok(ValueOwned::Struct {
                fields: Self::default_fields_value(&item_struct.fields, api_bundle)?,
            }),
            TypeOwned::Enum(item_enum) => {
                let variant = item_enum.variants.first().ok_or(anyhow!("Enum is empty"))?;
                let fields = Self::default_fields_value(&variant.fields, api_bundle)?;
                Ok(ValueOwned::Enum {
                    variant: variant.ident.clone(),
                    fields,
                })
            }
            TypeOwned::Option { .. } => Ok(ValueOwned::Option(None)),
            TypeOwned::Result { ok_ty, .. } => Ok(ValueOwned::Result(Err(Box::new(
                Self::default(ok_ty, api_bundle)?,
            )))),
            TypeOwned::Box(inner) => Ok(Self::default(inner, api_bundle)?),
            TypeOwned::Range(base) => Ok(ValueOwned::Range(
                default_numeric(base)?..default_numeric(base)?,
            )),
            TypeOwned::RangeInclusive(base) => Ok(ValueOwned::RangeInclusive(
                default_numeric(base)?..=default_numeric(base)?,
            )),
        }
    }

    pub fn default_fields_value(
        fields: &FieldsOwned,
        api_bundle: &ApiBundleOwned,
    ) -> Result<FieldsValueOwned> {
        match fields {
            FieldsOwned::Named(named) => {
                let mut named_values = vec![];
                for field in named {
                    let name = field.ident.clone().unwrap_or_default();
                    let value = ValueOwned::default(&field.ty, api_bundle)?;
                    named_values.push((name, value));
                }
                Ok(FieldsValueOwned::Named(named_values))
            }
            FieldsOwned::Unnamed(unnamed) => {
                let mut unnamed_values = vec![];
                for field in unnamed {
                    let value = ValueOwned::default(&field.ty, api_bundle)?;
                    unnamed_values.push(value);
                }
                Ok(FieldsValueOwned::Unnamed(unnamed_values))
            }
            FieldsOwned::Unit => Ok(FieldsValueOwned::Unit),
        }
    }
}

/// Base type of a numeric type, SubType and ShiftScale are serialized as their base type.
pub(crate) fn numeric_base(any: &NumericAnyTypeOwned) -> &NumericBaseType {
    match any {
        NumericAnyTypeOwned::Base(base)
        | NumericAnyTypeOwned::SubType { base, .. }
        | NumericAnyTypeOwned::ShiftScale { base, .. } => base,
    }
}

fn default_numeric(base: &NumericBaseType) -> Result<NumericValue> {
    Ok(match base {
        NumericBaseType::UB(bits) => unsigned_value(bits.0, 0),
        NumericBaseType::IB(bits) => signed_value(bits.0, 0),
        NumericBaseType::F16
        | NumericBaseType::ULeb32
        | NumericBaseType::ULeb64
        | NumericBaseType::ULeb128
        | NumericBaseType::ILeb32
        | NumericBaseType::ILeb64
        | NumericBaseType::ILeb128 => bail!("numeric type {base:?} is not supported yet"),
        base => base.default(),
    })
}

// ---------------------------------------------------------------------------------------------------------------------
// Deserialization

/// Read a value the way generated code reads a field (`BufReader::read`).
fn des_field(
    rd: &mut BufReader,
    ty: &TypeOwned,
    api_bundle: &ApiBundleOwned,
) -> Result<ValueOwned> {
    if ty.is_unsized(api_bundle)? {
        let len = rd.read_rev_len()?;
        let mut rd = rd.split(len)?;
        des_inner(&mut rd, ty, api_bundle)
    } else {
        des_inner(rd, ty, api_bundle)
    }
}

fn des_inner(
    rd: &mut BufReader,
    ty: &TypeOwned,
    api_bundle: &ApiBundleOwned,
) -> Result<ValueOwned> {
    match ty {
        TypeOwned::Bool => Ok(ValueOwned::Bool(rd.read_bool()?)),
        TypeOwned::NumericAny(numeric_any) => Ok(ValueOwned::Numeric(des_numeric(
            rd,
            numeric_base(numeric_any),
        )?)),
        TypeOwned::OutOfLine { type_idx } => {
            let ty = api_bundle.get_ty(type_idx.0)?.0;
            des_inner(rd, ty, api_bundle)
        }
        TypeOwned::Flag => bail!("flag type is not supported"),
        TypeOwned::String => Ok(ValueOwned::String(rd.read_str()?.to_string())),
        TypeOwned::Vec(inner_ty) => {
            let len = rd.read_rev_len()?;
            let mut items = Vec::with_capacity(len.min(rd.bytes_left() + 1));
            for _ in 0..len {
                items.push(des_field(rd, inner_ty, api_bundle)?);
            }
            Ok(ValueOwned::Vec(items))
        }
        TypeOwned::Array { len, ty } => {
            let mut items = vec![];
            for _ in 0..len.0 {
                items.push(des_field(rd, ty, api_bundle)?);
            }
            Ok(ValueOwned::Array(items))
        }
        TypeOwned::Tuple(types) => {
            let mut values = vec![];
            for ty in types {
                values.push(des_field(rd, ty, api_bundle)?);
            }
            Ok(ValueOwned::Tuple(values))
        }
        TypeOwned::Struct(struct_def) => {
            let fields = des_fields(rd, &struct_def.fields, api_bundle)?;
            Ok(ValueOwned::Struct { fields })
        }
        TypeOwned::Enum(enum_def) => {
            let discriminant = match enum_def.repr {
                Repr::Nibble => rd.read_nib_value()? as u32,
                Repr::BitAligned(bits) => rd.read_un32(bits)?,
                Repr::UNib32 => rd.read_unib32()?,
                Repr::ByteAlignedU8 => rd.read_u8()? as u32,
                Repr::ByteAlignedU16 => rd.read_u16()? as u32,
                Repr::ByteAlignedU32 => rd.read_u32()?,
            };
            let Some(variant) = enum_def
                .variants
                .iter()
                .find(|v| v.discriminant.0 == discriminant)
            else {
                bail!(
                    "enum '{}' does not have a variant with discriminant {discriminant} (newer version or malformed data)",
                    enum_def.ident
                );
            };
            let fields = des_fields(rd, &variant.fields, api_bundle)?;
            Ok(ValueOwned::Enum {
                variant: variant.ident.to_string(),
                fields,
            })
        }
        TypeOwned::Option { some_ty } => {
            if rd.read_bool()? {
                let value = des_field(rd, some_ty, api_bundle)?;
                Ok(ValueOwned::Option(Some(Box::new(value))))
            } else {
                Ok(ValueOwned::Option(None))
            }
        }
        TypeOwned::Result { ok_ty, err_ty } => {
            if rd.read_bool()? {
                let value = des_field(rd, ok_ty, api_bundle)?;
                Ok(ValueOwned::Result(Ok(Box::new(value))))
            } else {
                let value = des_field(rd, err_ty, api_bundle)?;
                Ok(ValueOwned::Result(Err(Box::new(value))))
            }
        }
        // Box<T> is Unsized itself (its size is handled by des_field), T is read directly inside it
        TypeOwned::Box(inner) => des_inner(rd, inner, api_bundle),
        TypeOwned::Range(base) => {
            let start = des_numeric(rd, base)?;
            let end = des_numeric(rd, base)?;
            Ok(ValueOwned::Range(start..end))
        }
        TypeOwned::RangeInclusive(base) => {
            let start = des_numeric(rd, base)?;
            let end = des_numeric(rd, base)?;
            Ok(ValueOwned::RangeInclusive(start..=end))
        }
    }
}

fn des_fields(
    rd: &mut BufReader,
    fields: &FieldsOwned,
    api_bundle: &ApiBundleOwned,
) -> Result<FieldsValueOwned> {
    Ok(match fields {
        FieldsOwned::Named(defs) => {
            let mut values = vec![];
            for def in defs {
                let name = def.ident.clone().unwrap_or_default();
                values.push((name, des_struct_field(rd, def, api_bundle)?));
            }
            FieldsValueOwned::Named(values)
        }
        FieldsOwned::Unnamed(defs) => {
            let mut values = vec![];
            for def in defs {
                values.push(des_struct_field(rd, def, api_bundle)?);
            }
            FieldsValueOwned::Unnamed(values)
        }
        FieldsOwned::Unit => FieldsValueOwned::Unit,
    })
}

/// Evolved fields with a `#[default = ..]` are read as their default when data ends (sent by an older version).
fn des_struct_field(
    rd: &mut BufReader,
    def: &FieldOwned,
    api_bundle: &ApiBundleOwned,
) -> Result<ValueOwned> {
    let value = des_field(rd, &def.ty, api_bundle);
    match (value, &def.default) {
        (Ok(value), _) => Ok(value),
        (Err(_), Some(_)) => ValueOwned::default(&def.ty, api_bundle),
        (Err(e), None) => Err(e),
    }
}

fn des_numeric(rd: &mut BufReader, base_ty: &NumericBaseType) -> Result<NumericValue> {
    Ok(match base_ty {
        NumericBaseType::Nibble => NumericValue::Nibble(rd.read_nib()?),
        NumericBaseType::U8 => NumericValue::U8(rd.read_u8()?),
        NumericBaseType::U16 => NumericValue::U16(rd.read_u16()?),
        NumericBaseType::U32 => NumericValue::U32(rd.read_u32()?),
        NumericBaseType::UNib32 => NumericValue::UNib32(rd.read_unib32()?),
        NumericBaseType::U64 => NumericValue::U64(rd.read_u64()?),
        NumericBaseType::U128 => NumericValue::U128(rd.read_u128()?),
        NumericBaseType::I8 => NumericValue::I8(rd.read_i8()?),
        NumericBaseType::I16 => NumericValue::I16(rd.read_i16()?),
        NumericBaseType::I32 => NumericValue::I32(rd.read_i32()?),
        NumericBaseType::I64 => NumericValue::I64(rd.read_i64()?),
        NumericBaseType::I128 => NumericValue::I128(rd.read_i128()?),
        NumericBaseType::F32 => NumericValue::F32(rd.read_f32()?),
        NumericBaseType::F64 => NumericValue::F64(rd.read_f64()?),
        NumericBaseType::UB(bits) => {
            let bits = bits.0;
            unsigned_value(bits, rd.read_un64(bits)?)
        }
        NumericBaseType::IB(bits) => {
            let bits = bits.0;
            let raw = rd.read_un64(bits)?;
            // sign extend
            let shift = 64 - bits as u32;
            let value = ((raw << shift) as i64) >> shift;
            signed_value(bits, value)
        }
        u => bail!("numeric type {u:?} is not supported yet"),
    })
}

/// Smallest standard unsigned value to hold `bits`-bit number.
fn unsigned_value(bits: u8, value: u64) -> NumericValue {
    match bits {
        0..=8 => NumericValue::U8(value as u8),
        9..=16 => NumericValue::U16(value as u16),
        17..=32 => NumericValue::U32(value as u32),
        _ => NumericValue::U64(value),
    }
}

/// Smallest standard signed value to hold `bits`-bit number.
fn signed_value(bits: u8, value: i64) -> NumericValue {
    match bits {
        0..=8 => NumericValue::I8(value as i8),
        9..=16 => NumericValue::I16(value as i16),
        17..=32 => NumericValue::I32(value as i32),
        _ => NumericValue::I64(value),
    }
}

// ---------------------------------------------------------------------------------------------------------------------
// Serialization

/// Write a value the way generated code writes a field (`BufWriter::write`).
fn ser_field(
    wr: &mut BufWriterOwned,
    value: &ValueOwned,
    ty: &TypeOwned,
    api_bundle: &ApiBundleOwned,
) -> Result<()> {
    if ty.is_unsized(api_bundle)? {
        let builder = UnsizedBuilderOwned::new(wr)?;
        ser_inner(wr, value, ty, api_bundle)?;
        builder.finish(wr)?;
    } else {
        ser_inner(wr, value, ty, api_bundle)?;
    }
    Ok(())
}

fn ser_inner(
    wr: &mut BufWriterOwned,
    value: &ValueOwned,
    ty: &TypeOwned,
    api_bundle: &ApiBundleOwned,
) -> Result<()> {
    let mismatch = || anyhow!("expected {}, got {value:?}", type_name(ty, api_bundle));
    match ty {
        TypeOwned::OutOfLine { type_idx } => {
            let ty = api_bundle.get_ty(type_idx.0)?.0;
            ser_inner(wr, value, ty, api_bundle)?;
        }
        TypeOwned::Bool => {
            let ValueOwned::Bool(value) = value else {
                return Err(mismatch());
            };
            wr.write_bool(*value)?;
        }
        TypeOwned::NumericAny(any) => {
            let ValueOwned::Numeric(value) = value else {
                return Err(mismatch());
            };
            ser_numeric(wr, value, numeric_base(any))?;
        }
        TypeOwned::Flag => bail!("flag type is not supported"),
        TypeOwned::String => {
            let ValueOwned::String(value) = value else {
                return Err(mismatch());
            };
            wr.write_str(value)?;
        }
        TypeOwned::Vec(inner_ty) => {
            let (ValueOwned::Vec(items) | ValueOwned::Array(items)) = value else {
                return Err(mismatch());
            };
            wr.write_rev_len(items.len())?;
            for item in items {
                ser_field(wr, item, inner_ty, api_bundle)?;
            }
        }
        TypeOwned::Array { len, ty: inner_ty } => {
            let (ValueOwned::Array(items) | ValueOwned::Vec(items)) = value else {
                return Err(mismatch());
            };
            if items.len() != len.0 as usize {
                bail!(
                    "expected an array of {} elements, got {}",
                    len.0,
                    items.len()
                );
            }
            for item in items {
                ser_field(wr, item, inner_ty, api_bundle)?;
            }
        }
        TypeOwned::Tuple(types) => {
            let ValueOwned::Tuple(values) = value else {
                return Err(mismatch());
            };
            if values.len() != types.len() {
                bail!(
                    "expected a tuple of {} elements, got {}",
                    types.len(),
                    values.len()
                );
            }
            for (value, ty) in values.iter().zip(types) {
                ser_field(wr, value, ty, api_bundle)?;
            }
        }
        TypeOwned::Struct(item_struct) => {
            let ValueOwned::Struct { fields } = value else {
                return Err(mismatch());
            };
            ser_fields(
                wr,
                fields,
                &item_struct.fields,
                &item_struct.ident,
                api_bundle,
            )?;
        }
        TypeOwned::Enum(item_enum) => {
            let ValueOwned::Enum { variant, fields } = value else {
                return Err(mismatch());
            };
            let variant_def = item_enum
                .variants
                .iter()
                .find(|v| &v.ident == variant)
                .ok_or_else(|| {
                    anyhow!(
                        "enum {} does not have variant {variant}, expected one of: {}",
                        item_enum.ident,
                        variant_names(item_enum)
                    )
                })?;
            write_discriminant(wr, item_enum, variant_def.discriminant.0)?;
            let path = format!("{}::{}", item_enum.ident, variant_def.ident);
            ser_fields(wr, fields, &variant_def.fields, &path, api_bundle)?;
        }
        TypeOwned::Option { some_ty } => {
            let ValueOwned::Option(value) = value else {
                return Err(mismatch());
            };
            wr.write_bool(value.is_some())?;
            if let Some(value) = value {
                ser_field(wr, value, some_ty, api_bundle)?;
            }
        }
        TypeOwned::Result { ok_ty, err_ty } => {
            let ValueOwned::Result(value) = value else {
                return Err(mismatch());
            };
            wr.write_bool(value.is_ok())?;
            match value {
                Ok(value) => ser_field(wr, value, ok_ty, api_bundle)?,
                Err(value) => ser_field(wr, value, err_ty, api_bundle)?,
            }
        }
        // Box<T> is Unsized itself (its size is handled by ser_field), T is written directly inside it
        TypeOwned::Box(inner) => ser_inner(wr, value, inner, api_bundle)?,
        TypeOwned::Range(base) => {
            let ValueOwned::Range(range) = value else {
                return Err(mismatch());
            };
            ser_numeric(wr, &range.start, base)?;
            ser_numeric(wr, &range.end, base)?;
        }
        TypeOwned::RangeInclusive(base) => {
            let ValueOwned::RangeInclusive(range) = value else {
                return Err(mismatch());
            };
            ser_numeric(wr, range.start(), base)?;
            ser_numeric(wr, range.end(), base)?;
        }
    }
    Ok(())
}

fn type_name(ty: &TypeOwned, api_bundle: &ApiBundleOwned) -> String {
    ty.human_name(false, api_bundle)
        .unwrap_or_else(|_| format!("{ty:?}"))
}

fn variant_names(item_enum: &ItemEnumOwned) -> String {
    item_enum
        .variants
        .iter()
        .map(|v| v.ident.as_str())
        .collect::<Vec<_>>()
        .join(", ")
}

fn write_discriminant(
    wr: &mut BufWriterOwned,
    item_enum: &ItemEnumOwned,
    discriminant: u32,
) -> Result<()> {
    let max = match item_enum.repr {
        Repr::Nibble => 0xF,
        Repr::BitAligned(bits) if bits < 32 => (1u32 << bits) - 1,
        Repr::BitAligned(_) | Repr::UNib32 | Repr::ByteAlignedU32 => u32::MAX,
        Repr::ByteAlignedU8 => u8::MAX as u32,
        Repr::ByteAlignedU16 => u16::MAX as u32,
    };
    if discriminant > max {
        bail!(
            "enum {} discriminant {discriminant} does not fit into its repr {:?}",
            item_enum.ident,
            item_enum.repr
        );
    }
    match item_enum.repr {
        Repr::Nibble => wr.write_nib_masked(discriminant as u8)?,
        Repr::BitAligned(bits) => wr.write_un32(bits, discriminant)?,
        Repr::UNib32 => wr.write_unib32(discriminant)?,
        Repr::ByteAlignedU8 => wr.write_u8(discriminant as u8)?,
        Repr::ByteAlignedU16 => wr.write_u16(discriminant as u16)?,
        Repr::ByteAlignedU32 => wr.write_u32(discriminant)?,
    }
    Ok(())
}

/// Named fields are matched by name, a missing one can only be an `Option` (written as `None`) or a field with a
/// default value.
fn ser_fields(
    wr: &mut BufWriterOwned,
    fields: &FieldsValueOwned,
    fields_def: &FieldsOwned,
    path: &str,
    api_bundle: &ApiBundleOwned,
) -> Result<()> {
    match (fields_def, fields) {
        (FieldsOwned::Named(defs), FieldsValueOwned::Named(values)) => {
            for (name, _) in values {
                if !defs.iter().any(|d| d.ident.as_deref() == Some(name)) {
                    bail!(
                        "{path} does not have field '{name}', expected: {}",
                        field_names(defs)
                    );
                }
            }
            for def in defs {
                let name = def.ident.as_deref().unwrap_or_default();
                let value = values.iter().find(|(n, _)| n == name).map(|(_, v)| v);
                match value {
                    Some(value) => ser_field(wr, value, &def.ty, api_bundle)?,
                    None => {
                        let fallback = match (&def.default, def.ty.get_in_line(api_bundle)?) {
                            (Some(_), _) => ValueOwned::default(&def.ty, api_bundle)?,
                            (None, TypeOwned::Option { .. }) => ValueOwned::Option(None),
                            _ => bail!("{path}: missing field '{name}'"),
                        };
                        ser_field(wr, &fallback, &def.ty, api_bundle)?;
                    }
                }
            }
        }
        (FieldsOwned::Unnamed(defs), FieldsValueOwned::Unnamed(values)) => {
            if defs.len() != values.len() {
                bail!(
                    "{path}: expected {} fields, got {}",
                    defs.len(),
                    values.len()
                );
            }
            for (def, value) in defs.iter().zip(values) {
                ser_field(wr, value, &def.ty, api_bundle)?;
            }
        }
        (FieldsOwned::Unit, FieldsValueOwned::Unit) => {}
        (FieldsOwned::Named(defs), _) => {
            bail!("{path}: expected named fields: {}", field_names(defs))
        }
        (FieldsOwned::Unnamed(defs), _) => {
            bail!("{path}: expected {} unnamed fields", defs.len())
        }
        (FieldsOwned::Unit, _) => bail!("{path}: expected no fields"),
    }
    Ok(())
}

fn field_names(defs: &[FieldOwned]) -> String {
    defs.iter()
        .filter_map(|d| d.ident.as_deref())
        .collect::<Vec<_>>()
        .join(", ")
}

fn ser_numeric(
    wr: &mut BufWriterOwned,
    value: &NumericValue,
    base_ty: &NumericBaseType,
) -> Result<()> {
    let out_of_range = || anyhow!("{value:?} is out of range for {base_ty:?}");
    macro_rules! int {
        ($t:ty) => {
            <$t>::try_from(int_value(value)?).map_err(|_| out_of_range())?
        };
    }
    match base_ty {
        NumericBaseType::Nibble => {
            let nib = Nibble::new(int!(u8)).ok_or_else(out_of_range)?;
            wr.write_nib(nib)?
        }
        NumericBaseType::U8 => wr.write_u8(int!(u8))?,
        NumericBaseType::U16 => wr.write_u16(int!(u16))?,
        NumericBaseType::U32 => wr.write_u32(int!(u32))?,
        NumericBaseType::UNib32 => wr.write_unib32(int!(u32))?,
        NumericBaseType::U64 => wr.write_u64(int!(u64))?,
        NumericBaseType::U128 => match value {
            NumericValue::U128(v) => wr.write_u128(*v)?,
            _ => wr.write_u128(int!(u128))?,
        },
        NumericBaseType::I8 => wr.write_i8(int!(i8))?,
        NumericBaseType::I16 => wr.write_i16(int!(i16))?,
        NumericBaseType::I32 => wr.write_i32(int!(i32))?,
        NumericBaseType::I64 => wr.write_i64(int!(i64))?,
        NumericBaseType::I128 => wr.write_i128(int!(i128))?,
        NumericBaseType::F32 => wr.write_f32(float_value(value)? as f32)?,
        NumericBaseType::F64 => wr.write_f64(float_value(value)?)?,
        NumericBaseType::UB(bits) => {
            let bits = bits.0;
            let v = int!(u64);
            if bits < 64 && v >> bits != 0 {
                return Err(out_of_range());
            }
            wr.write_un64(bits, v)?
        }
        NumericBaseType::IB(bits) => {
            let bits = bits.0;
            let v = int!(i64);
            let (min, max) = (-(1i128 << (bits - 1)), (1i128 << (bits - 1)) - 1);
            if (v as i128) < min || (v as i128) > max {
                return Err(out_of_range());
            }
            let mask = if bits == 64 {
                u64::MAX
            } else {
                (1u64 << bits) - 1
            };
            wr.write_un64(bits, v as u64 & mask)?
        }
        u => bail!("numeric type {u:?} is not supported yet"),
    }
    Ok(())
}

/// Integer value of any integer variant, so that e.g. `U8(1)` can be written as `u32`. Range is checked by the caller.
fn int_value(value: &NumericValue) -> Result<i128> {
    Ok(match value {
        NumericValue::Nibble(v) => v.value() as i128,
        NumericValue::U8(v) => *v as i128,
        NumericValue::U16(v) => *v as i128,
        NumericValue::U32(v) | NumericValue::UNib32(v) => *v as i128,
        NumericValue::U64(v) => *v as i128,
        NumericValue::U128(v) => i128::try_from(*v).map_err(|_| anyhow!("{v} is out of range"))?,
        NumericValue::I8(v) => *v as i128,
        NumericValue::I16(v) => *v as i128,
        NumericValue::I32(v) => *v as i128,
        NumericValue::I64(v) => *v as i128,
        NumericValue::I128(v) => *v,
        u => bail!("expected an integer, got {u:?}"),
    })
}

fn float_value(value: &NumericValue) -> Result<f64> {
    Ok(match value {
        NumericValue::F32(v) => *v as f64,
        NumericValue::F64(v) => *v,
        other => int_value(other)? as f64,
    })
}
