[package]
name = "ww_si"
version = "0.1.0"
authors.workspace = true
description = "Statically and dynamically typed SI values"
edition.workspace = true
license.workspace = true
repository = "https://github.com/vhrdtech/ww_stdlib"

[features]
default = ["std"]
std = ["shrink_wrap/std", "ww_numeric/std"]
defmt = ["dep:defmt", "shrink_wrap/defmt", "ww_numeric/defmt"]

[dependencies]
defmt = { workspace = true, optional = true }
shrink_wrap.workspace = true
ww_numeric.workspace = true
