[package]
name = "wire_weaver"
edition.workspace = true
version.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
documentation = "https://vhrdtech.github.io/wire_weaver"

[features]
default = ["std"]
std = ["shrink_wrap/std", "ww_version/std"]
defmt = ["dep:defmt", "shrink_wrap/defmt", "ww_version/defmt"]
serde = ["shrink_wrap/serde"]

[dependencies]
defmt = { workspace = true, optional = true }
shrink_wrap = { workspace = true, default-features = false }
wire_weaver_derive.workspace = true
ww_version = { workspace = true, default-features = false }
