use proc_macro2::{Ident, TokenStream};
use shrink_wrap_core::ast::{ObjectSize, Repr};
use syn::parse::{Parse, ParseStream};
use syn::{Path, Token};

#[allow(dead_code)]
pub(crate) struct Args {
    /// Borrowed is generated by default, even if nothing is specified. Opt out by gating it
    /// behind a `cfg` predicate captured verbatim from `borrowed(..)`, e.g. `borrowed(feature = "std")`.
    pub(crate) borrowed: Option<TokenStream>,
    /// Bare `owned` unconditionally generates the owned type; `owned(..)` gates it behind a
    /// `cfg` predicate captured verbatim, e.g. `owned(feature = "std")`.
    pub(crate) owned: Option<Option<TokenStream>>,
    /// `cfg_attr(condition, attr, ..)` argument lists captured verbatim, spliced into
    /// `#[cfg_attr(..)]` on both types. Can be repeated.
    pub(crate) cfg_attr: Vec<TokenStream>,
    /// Same as `cfg_attr`, but applied to the generated owned type.
    pub(crate) cfg_attr_owned: Vec<TokenStream>,
    /// Same as `cfg_attr`, but applied to the generated borrowed type.
    pub(crate) cfg_attr_borrowed: Vec<TokenStream>,
    pub(crate) derive: Vec<Path>,
    pub(crate) derive_owned: Vec<Path>,
    pub(crate) derive_borrowed: Vec<Path>,
    pub(crate) size_assumption: Option<ObjectSize>,
    pub(crate) ww_repr: Option<Repr>,
    pub(crate) discriminants_enum: bool,
}

impl Parse for Args {
    fn parse(input: ParseStream) -> syn::Result<Self> {
        let mut discriminants_enum = false;
        let mut borrowed = None;
        let mut owned = None;
        let mut cfg_attr = Vec::new();
        let mut cfg_attr_owned = Vec::new();
        let mut cfg_attr_borrowed = Vec::new();
        let mut derive = Vec::new();
        let mut derive_owned = Vec::new();
        let mut derive_borrowed = Vec::new();
        let mut size_assumption = None;
        let mut ww_repr = None;

        while !input.is_empty() {
            let ident: Ident = input.parse()?;
            match ident.to_string().as_str() {
                "borrowed" => {
                    borrowed = Some(parse_paren_token_stream(input)?);
                }
                "owned" => {
                    set_owned_directive(&mut owned, input, &ident)?;
                }
                "cfg_attr" => {
                    cfg_attr.push(parse_paren_token_stream(input)?);
                }
                "cfg_attr_owned" => {
                    cfg_attr_owned.push(parse_paren_token_stream(input)?);
                }
                "cfg_attr_borrowed" => {
                    cfg_attr_borrowed.push(parse_paren_token_stream(input)?);
                }
                "derive" => {
                    derive = parse_path_list_paren(input)?;
                }
                "derive_owned" => {
                    derive_owned = parse_path_list_paren(input)?;
                }
                "derive_borrowed" => {
                    derive_borrowed = parse_path_list_paren(input)?;
                }
                "final_structure" => {
                    set_size_assumption(
                        &mut size_assumption,
                        ObjectSize::UnsizedFinalStructure,
                        &ident,
                    )?;
                }
                "self_describing" => {
                    set_size_assumption(&mut size_assumption, ObjectSize::SelfDescribing, &ident)?;
                }
                "sized" => {
                    set_size_assumption(
                        &mut size_assumption,
                        ObjectSize::Sized { size_bits: 0 },
                        &ident,
                    )?;
                }
                "ww_repr" => {
                    input.parse::<Token![=]>()?;
                    let repr_ident: Ident = input.parse()?;
                    ww_repr = Some(Repr::parse_str(repr_ident.to_string().as_str()).ok_or_else(
                        || {
                            syn::Error::new(
                                repr_ident.span(),
                                "expected one of: unib32, nib, u1..u32, ub<N>",
                            )
                        },
                    )?);
                }
                "discriminants" => {
                    discriminants_enum = true;
                }
                u => {
                    return Err(syn::Error::new(
                        ident.span(),
                        format!(
                            "unsupported directive '{u}', expected one of: {SUPPORTED_DIRECTIVES}"
                        ),
                    ));
                }
            }

            if input.is_empty() {
                break;
            }
            input.parse::<Token![,]>()?;
        }

        Ok(Args {
            discriminants_enum,
            borrowed,
            owned,
            cfg_attr,
            cfg_attr_owned,
            cfg_attr_borrowed,
            derive,
            derive_owned,
            derive_borrowed,
            size_assumption,
            ww_repr,
        })
    }
}

const SUPPORTED_DIRECTIVES: &str = "borrowed(..), owned, owned(..), \
cfg_attr(..), cfg_attr_owned(..), cfg_attr_borrowed(..), \
derive(..), derive_owned(..), derive_borrowed(..), \
final_structure, self_describing, sized, ww_repr=<u1,u2,..,nib,unib32,u8,..>, discriminants";

/// Parses a required `(Path1, Path2, ..)`, like Rust's own `#[derive(..)]`
fn parse_path_list_paren(input: ParseStream) -> syn::Result<Vec<Path>> {
    let content;
    syn::parenthesized!(content in input);
    let paths = syn::punctuated::Punctuated::<Path, Token![,]>::parse_terminated(&content)?;
    Ok(paths.into_iter().collect())
}

/// Parses a required `(..)`, capturing its content verbatim without interpreting it - used for
/// `cfg_attr(condition, attr, ..)` argument lists, whose `condition` follows its own grammar
/// (`any`/`all`/`not`, bare idents, `key = "value"`) that isn't worth re-parsing here since the
/// whole thing is only ever spliced back into a generated `#[cfg_attr(..)]`.
fn parse_paren_token_stream(input: ParseStream) -> syn::Result<TokenStream> {
    let content;
    syn::parenthesized!(content in input);
    content.parse()
}

/// Parses `(..)` if present, returning `None` when the directive is a bare flag.
fn parse_optional_paren_token_stream(input: ParseStream) -> syn::Result<Option<TokenStream>> {
    if input.peek(syn::token::Paren) {
        Ok(Some(parse_paren_token_stream(input)?))
    } else {
        Ok(None)
    }
}

/// Sets `size_assumption`, erroring if it was already set by an earlier directive since
/// `final_structure`, `self_describing` and `sized` are mutually exclusive.
fn set_size_assumption(
    size_assumption: &mut Option<ObjectSize>,
    value: ObjectSize,
    ident: &Ident,
) -> syn::Result<()> {
    if size_assumption.is_some() {
        return Err(syn::Error::new(
            ident.span(),
            "'final_structure', 'self_describing' and 'sized' are mutually exclusive, only one can be specified",
        ));
    }
    *size_assumption = Some(value);
    Ok(())
}

/// Sets `owned`, erroring if it was already specified (either bare or with a `= "string"` value).
fn set_owned_directive(
    slot: &mut Option<Option<TokenStream>>,
    input: ParseStream,
    ident: &Ident,
) -> syn::Result<()> {
    if slot.is_some() {
        return Err(syn::Error::new(
            ident.span(),
            format!(
                "'{ident}' was already specified, '{ident}' alone is unconditional, '{ident}(..)' will add #[cfg(..)] with the given predicate"
            ),
        ));
    }
    *slot = Some(parse_optional_paren_token_stream(input)?);
    Ok(())
}

#[cfg(test)]
mod args_parse_tests {
    use super::Args;
    use quote::quote;
    use syn::parse2;

    #[test]
    fn parses_all_directives() {
        let ts = quote! {
            discriminants, borrowed(feature = "alloc"), owned(feature = "alloc"),
            cfg_attr(feature = "defmt", derive(defmt::Format)),
            cfg_attr_owned(feature = "std", derive(Debug)),
            cfg_attr_borrowed(not(feature = "std"), derive(Copy)),
            derive(Debug, Clone), derive_owned(Debug), derive_borrowed(Debug),
            final_structure, ww_repr = u16
        };
        let args: Args = parse2(ts).unwrap();
        assert!(args.discriminants_enum);
        assert!(args.borrowed.is_some());
        assert!(args.owned.flatten().is_some());
        assert_eq!(args.cfg_attr.len(), 1);
        assert_eq!(args.cfg_attr_owned.len(), 1);
        assert_eq!(args.cfg_attr_borrowed.len(), 1);
        assert_eq!(args.derive.len(), 2);
        assert_eq!(args.derive_owned.len(), 1);
        assert_eq!(args.derive_borrowed.len(), 1);
    }

    #[test]
    fn rejects_duplicate_owned() {
        let ts = quote! { owned, owned };
        assert!(parse2::<Args>(ts).is_err());

        let ts = quote! { owned(feature = "a"), owned(feature = "b") };
        assert!(parse2::<Args>(ts).is_err());
    }

    #[test]
    fn cfg_attr_directives_capture_multiple_verbatim() {
        for directive in ["cfg_attr", "cfg_attr_owned", "cfg_attr_borrowed"] {
            let ident = proc_macro2::Ident::new(directive, proc_macro2::Span::call_site());
            let ts = quote! {
                #ident(feature = "defmt"),
                #ident(any(feature = "std", feature = "alloc")),
                #ident(not(target_os = "none"))
            };
            let args: Args = parse2(ts).unwrap();
            let predicates = match directive {
                "cfg_attr" => &args.cfg_attr,
                "cfg_attr_owned" => &args.cfg_attr_owned,
                "cfg_attr_borrowed" => &args.cfg_attr_borrowed,
                _ => unreachable!(),
            };
            assert_eq!(predicates.len(), 3);
            assert_eq!(
                predicates[0].to_string(),
                quote! { feature = "defmt" }.to_string()
            );
            assert_eq!(
                predicates[1].to_string(),
                quote! { any(feature = "std", feature = "alloc") }.to_string()
            );
        }
    }

    #[test]
    fn cfg_attr_directives_require_parens() {
        for directive in ["cfg_attr", "cfg_attr_owned", "cfg_attr_borrowed"] {
            let ident = proc_macro2::Ident::new(directive, proc_macro2::Span::call_site());
            let ts = quote! { #ident = "defmt" };
            assert!(parse2::<Args>(ts).is_err());
        }
    }

    #[test]
    fn rejects_conflicting_size_assumption() {
        let ts = quote! { final_structure, sized };
        let res: syn::Result<Args> = parse2(ts);
        assert!(res.is_err());

        let ts = quote! { self_describing, self_describing };
        let res: syn::Result<Args> = parse2(ts);
        assert!(res.is_err());
    }

    #[test]
    fn rejects_unknown() {
        let ts = quote! { bogus };
        let res: syn::Result<Args> = parse2(ts);
        let err = res.map(|_| ()).unwrap_err();
        assert!(err.to_string().contains("unsupported directive 'bogus'"));
        assert!(err.to_string().contains("expected one of:"));
        assert!(err.to_string().contains("derive_borrowed"));
    }

    #[test]
    fn ww_repr_bad_value_errors() {
        let ts = quote! { ww_repr = not_a_repr };
        let res: syn::Result<Args> = parse2(ts);
        assert!(res.is_err());
    }

    #[test]
    fn derive_lists_accept_paren_paths() {
        for directive in ["derive", "derive_owned", "derive_borrowed"] {
            let ident = proc_macro2::Ident::new(directive, proc_macro2::Span::call_site());
            let ts = quote! { #ident(Debug, Clone, PartialEq) };
            assert!(parse2::<Args>(ts).is_ok());

            // paths, like core::fmt::Debug, are allowed too
            let ts = quote! { #ident(Debug, core::fmt::Debug) };
            assert!(parse2::<Args>(ts).is_ok());

            // trailing comma, like Rust's own #[derive(..)]
            let ts = quote! { #ident(Debug,) };
            assert!(parse2::<Args>(ts).is_ok());

            // empty list
            let ts = quote! { #ident() };
            assert!(parse2::<Args>(ts).is_ok());
        }
    }

    #[test]
    fn derive_lists_reject_invalid_syntax() {
        for directive in ["derive", "derive_owned", "derive_borrowed"] {
            let ident = proc_macro2::Ident::new(directive, proc_macro2::Span::call_site());

            // not parenthesized at all
            let ts = quote! { #ident = "Debug" };
            assert!(parse2::<Args>(ts).is_err());

            // not a path
            let ts = quote! { #ident(1) };
            assert!(parse2::<Args>(ts).is_err());
        }
    }

    #[test]
    fn owned_and_borrowed_accept_verbatim_predicate() {
        let ts = quote! { owned(feature = "alloc") };
        let args: Args = parse2(ts).unwrap();
        assert_eq!(
            args.owned.unwrap().unwrap().to_string(),
            quote! { feature = "alloc" }.to_string()
        );

        let ts = quote! { owned(any(feature = "std", feature = "alloc")) };
        assert!(parse2::<Args>(ts).is_ok());

        let ts = quote! { borrowed(not(feature = "no_std")) };
        let args: Args = parse2(ts).unwrap();
        assert_eq!(
            args.borrowed.unwrap().to_string(),
            quote! { not(feature = "no_std") }.to_string()
        );
    }

    #[test]
    fn owned_bare_is_unconditional() {
        let ts = quote! { owned };
        let args: Args = parse2(ts).unwrap();
        assert!(matches!(args.owned, Some(None)));
    }

    #[test]
    fn borrowed_requires_parens() {
        let ts = quote! { borrowed };
        assert!(parse2::<Args>(ts).is_err());

        let ts = quote! { borrowed = "alloc" };
        assert!(parse2::<Args>(ts).is_err());
    }
}
