[package]
name = "wire_weaver_usb_link"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
description = "Transport layer on top of USB packets, allowing multiple messages per packet"
license.workspace = true
repository.workspace = true

[features]
std = []
host = ["std", "wire_weaver/std"]
device = []
defmt = ["dep:defmt", "wire_weaver/defmt"]

[dependencies]
crc = "3.3.0"
defmt = { workspace = true, optional = true }
shrink_wrap.workspace = true
strum_macros = { workspace = true }
wire_weaver = { version = "0.4.0", path = "../wire_weaver", default-features = false }
ww_global.workspace = true

[dev-dependencies]
tokio = { version = "1.48", features = ["sync"] }
worst-executor = { version = "0.1.1", git = "https://github.com/romixlab/worst-executor.git" }
