[package]
name = "ww_can_bus"
version = "0.1.0"
authors.workspace = true
description = "CAN Bus types and API"
edition.workspace = true
license.workspace = true
repository = "https://github.com/vhrdtech/ww_stdlib"

[features]
default = ["std"]
std = ["wire_weaver/std"]
defmt = ["dep:defmt", "wire_weaver/defmt", "ww_numeric/std"]

[dependencies]
defmt = { workspace = true, optional = true }
wire_weaver = { workspace = true }
ww_numeric.workspace = true
ww_version.workspace = true
