[package]
name = "wire_weaver_derive"
edition.workspace = true
version.workspace = true
authors.workspace = true
description = "Derive macros of wire_weaver - API code generator for microcontrollers"
repository.workspace = true
license.workspace = true
documentation = "https://vhrdtech.github.io/wire_weaver"

[lib]
proc-macro = true

[dependencies]
convert_case.workspace = true
darling = "0.24"
pathsearch = "0.2"
proc-macro2 = { workspace = true }
quote = { workspace = true }
relative-path.workspace = true
subprocess = "1.2"
syn = { workspace = true }
wire_weaver_core.workspace = true
