[package]
name = "ww_numeric"
version = "0.2.0"
authors.workspace = true
description = "Various numeric types, subtypes, shift-scale"
edition.workspace = true
license.workspace = true
repository = "https://github.com/vhrdtech/ww_stdlib"

[features]
default = ["std"]
std = ["shrink_wrap/std"]
defmt = ["dep:defmt", "shrink_wrap/defmt"]
serde = ["dep:serde", "shrink_wrap/serde"]

[dependencies]
defmt = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
shrink_wrap.workspace = true
