[package]
name = "blinky_evolved"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
blinky_api = {workspace = true} # on purpose link to blinky_api here to demonstrate how #[since = ""] works
blinky_api_evolved.workspace = true
tokio = { workspace = true, features = ["sync", "rt"] }
wire_weaver.workspace = true
wire_weaver_client.workspace = true

[dev-dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
console.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing = "0.1"
tracing-subscriber.workspace = true
ww_self = { workspace = true }
