[package]
name = "blinky_py"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "blinky"
crate-type = ["cdylib"]

[dependencies]
blinky.workspace = true
pyo3.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread"] }
