[package]
name = "tests_common"
version = "0.1.0"
publish = false
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tokio = { workspace = true, features = ["sync", "rt", "time", "macros"] }
wire_weaver.workspace = true
wire_weaver_client = { workspace = true, features = ["in_process"] }
ww_client_server.workspace = true
ww_device.workspace = true
