[package]
name = "uart"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tokio = { workspace = true, features = ["sync", "rt"] }
uart_api.workspace = true
wire_weaver.workspace = true
wire_weaver_client.workspace = true
ww_si = { workspace = true, features = ["std"] }
ww_uart = { workspace = true, features = ["std"] }

[dev-dependencies]
anyhow.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing = "0.1"
tracing-subscriber.workspace = true

[[example]]
name = "uart_blocking"
path = "examples/blocking.rs"

[[example]]
name = "uart_simple"
path = "examples/simple.rs"
