[package]
name = "ww"
version = "0.1.0"
authors.workspace = true
description = "WireWeaver command line tool"
edition.workspace = true

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive", "env"] }
clap_complete = { version = "4.6", features = ["unstable-dynamic"] }
console = "0.16"
human-repr = "1.1"
indicatif = "0.18"
proc-macro2.workspace = true
ron = "0.12"
semver.workspace = true
shrink_wrap = { workspace = true, features = ["std"] }
syn.workspace = true
toml = "1"
toml_edit = "0.25"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tracing = "0.1"
tracing-subscriber = "0.3"
wire_weaver_client.workspace = true

wire_weaver_core = { path = "../wire_weaver_core" }
