[package]
name = "shrink_wrap"
edition.workspace = true
version = "0.2.0"
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Compact zero-copy wire format for microcontrollers using no allocator and supporting dynamic types."
readme = "../README.md"

[features]
default = ["std"]
std = ["serde/std"]
serde = ["dep:serde"]

defmt = ["dep:defmt"]

[dependencies]
defmt = { workspace = true, optional = true }
either = { version = "1", default-features = false }
paste = "1"
serde = { workspace = true, optional = true }
shrink_wrap_derive.workspace = true

[dev-dependencies]
hex-literal.workspace = true
