name: Publish Documentation

on:
  push:
    paths:
      - 'zensical.toml'
      - 'docs/**'

permissions:
  contents: write

jobs:

  documentation-job:
    runs-on: ubuntu-latest

    steps:
      - name: SCM Checkout
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v10.2.0

      - name: Build Documentation
        run: |
          uv run just build-docs
          touch site/.nojekyll

      - name: Deploy Documentation
        uses: JamesIves/github-pages-deploy-action@v4.9.0
        with:
          branch: gh-pages
          folder: site
          git-config-name: Github Action
          git-config-email: romix.lab@gmail.com
